jwt:
  secret: #####

spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mariadb://localhost:3306/omechu
    driver-class-name: org.mariadb.jdbc.Driver
    username: omechu
    password: ####
    connectionInitSql: "SET NAMES 'utf8mb4'"

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #show_sql: true
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ##########
            client-secret: ######
            scope:
              - email
              - profile

          kakao:
            client-id: ######
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

logging.level:
  org.hibernate.SQL: debug
  #org.hibernate.type: trace